# Generated by Django 4.2.5 on 2023-10-07 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('election_date', models.DateField(blank=True, null=True)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jover.person')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_manager', to='jover.person')),
                ('volunteers', models.ManyToManyField(related_name='campaign_volunteers', to='jover.person')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='materials/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jover.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jover.campaign')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jover.person')),
            ],
        ),
    ]
